version: '3.8'

services:
  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=student_db
      - SERVER_PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - student-api-network
    command: ['mysql', '3306', './api']
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=student_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - student-api-network
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  student-api-network:
    driver: bridge
